name: pull-requests

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Run tests
        run: |
          npm ci
          npm run test
